#!/bin/bash
SCRIPT_ROOT=$( cd `dirname $0`; pwd)
source $SCRIPT_ROOT/.env
cat <<EOF
CLIENT=$CLIENT
JUMPBOX_IP=$JUMPBOX_IP
POC_DOMAIN=$POC_DOMAIN 
AWS_HOSTED_ZONE_ID=$AWS_HOSTED_ZONE_ID 
CERT_EMAIL=$CERT_EMAIL 
ROOT_DOMAIN=$ROOT_DOMAIN
LOCAL_REGISTRY=$LOCAL_REGISTRY
EOF

