apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test
    version: v1
  name: test
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: http
  selector:
    app: test
    version: v1
