---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: tanzu-harbor-psp
  labels:
    heritage: Helm
    release: tanzu-harbor
    chart: harbor
    app: "harbor"
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
    - "*"
  hostNetwork: false
  hostPID: false
  hostIPC: false
  runAsUser:
    rule: "RunAsAny"
  runAsGroup:
    rule: "RunAsAny"
  seLinux:
    rule: "RunAsAny"
  supplementalGroups:
    rule: "RunAsAny"
  fsGroup:
    rule: "RunAsAny"
  readOnlyRootFilesystem: false

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: tanzu-harbor-psp-role
  labels:
    heritage: Helm
    release: tanzu-harbor
    chart: harbor
    app: "harbor"
rules:
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames:
      - tanzu-harbor-psp
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: tanzu-harbor-psp-role-binding
  labels:
    heritage: Helm
    release: tanzu-harbor
    chart: harbor
    app: "harbor"
roleRef:
  kind: Role
  name: tanzu-harbor-psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tanzu-harbor
